name: Cache

on:
  push:
    paths:
      - '.github/workflows/cache.yml'
      
jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - run: touch .cache
        
      - name: Cache
        uses: actions/cache@v3
        with:
          path: .cache
          key: Cache
