name: Docker

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/docker.yml'
      - 'Docker/**'
      
env:
  NAME: hello-world #镜像名称
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: waterlemons2k
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: Docker
          platforms: amd64,arm,arm64
          push: true
          tags: waterlemons2k/test:${{ env.NAME }}
