name: Docker Run Action

on:
  push:
    paths:
      - '.github/workflows/docker-run-action.yml'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Docker
        uses: addnab/docker-run-action@v3
        with:
          image: alpine
          run: |
            echo "Hello World!"
            echo "I'm running on Alpine $(cat /etc/alpine-release)!"
