name: Git auto commit

on:
  push:
    paths:
      - '.github/workflows/git-auto-commit.yml'
      
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v3
      
      - name: Create DATE file
        run: |
          echo $(date) > DATE
          
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add DATE
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
