name: Git allow empty

on:
  push:
    branches:
      - "main"
    tags:
      - "!**"
    paths:
      - '.github/workflows/git-allow-empty.yml'
      
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v3
          
      - name: Git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: empty commit"
          commit_options: '--allow-empty'
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          skip_dirty_check: true
