name: Git

on:
  push:
    paths:
      - '.github/workflows/git-auto-commit.yml'
      
jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v3
      
      - name: Create DATE file
        run: |
          echo $(date +%F) > DATE
          
      - name: Git auto commit
        id: git
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add DATE
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

      - name: Keepalive Workflow
        if: steps.git.outputs.changes_detected == 'false'
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: Empty commit to keep cron active
          committer_username: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
