name: GoReleaser

on:
  push:
    paths:
      - '.github/workflows/goreleaser.yml'
    tags:
      - 'v*'
      
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Set up Go
        uses: actions/setup-go@v3
        
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --rm-dist
          workdir: Go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
