name: If env

on:
  push:
    paths:
      - '.github/workflows/if-env.yml'
      
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo env
        if: ${{ env.FOO }}
        run: echo ${{ env.FOO }}
