name: Keepalive Workflow

on:
  push:
    paths:
      - '.github/workflows/keepalive-workflow.yml'
  
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: "chore: empty commit to keep cron active"
          committer_username: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
