name: Keepalive Workflow

on:
  push:
  
jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v1
